openapi: 3.0.3
info:
  title: Blanc app - OpenAPI 3.0
  description: Sport application
  contact:
    email: visual01@yandex.ru
  version: 1.0.0
tags:
  - name: auth
    description: all aboout authorization and authentication
    externalDocs:
      description: oauth2 docs
      url: https://datatracker.ietf.org/doc/html/rfc6749
paths:
  /auth/callback:
    get:
      tags:
        - auth
      summary: callback для авторизации
      description: fsf
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string   
  /auth/realms/{realm_name}/protocol/openid-connect/auth:
    get:
      tags:
        - auth
      summary: ссылка на экран авторизации
      description: 'example: GET /auth?response_type=code&client_id=s6BhdRkqt3&state=xyz
        &redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcallback'
      parameters:
        - name: realm_name
          description: Название реалма в keycloak
          in: path
          required: true
          schema:
            type: string
        - name: response_type
          description: Способ авторизации (flow)
          in: query
          required: true
          schema:
            type: string
            enum: [code]
        - name: client_id
          description: Идентификатор клиента (приложения) в указанном реалме
          in: query
          required: true
          schema:
            type: string
            example: clientId
        - name: state
          description: Рандомное значение для маппинга запроса с ответом в callback
          in: query
          required: true
          schema:
            type: string
        - name: redirect_uri
          description: url адресс callback куда будет направлен ползователь после авторизации
          in: query
          required: false
          schema:
            type: string
        - name: scope
          in: query
          required: false
          schema:
            type: string
          description: Набор видимости атрибутов, к которым пользователь дает доступ при авторизации
      responses:
        '200':
          description: HTML страница авторизации
  /auth/realms/{realmName}/protocol/openid-connect/auth2:
    post:
      tags:
        - auth
      parameters:
        - name: realmName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string   
